### ISSUE TITLE
ValueError: Expected 2D array, got 1D array instead:array=[].

### ISSUE THREAD

**Issue by alzami1986** [Menelau/DESlib#74]
Hello, we found error regarding the METADES implementation, the error as follows:
Traceback (most recent call last):
  File "/home/miner/anaconda2/envs/python35/lib/python3.5/site-packages/deslib/des/meta_des.py", line 132, in fit
    check_is_fitted(self.meta_classifier, "classes_")
  File "/home/miner/anaconda2/envs/python35/lib/python3.5/site-packages/sklearn/utils/validation.py", line 768, in check_is_fitted
    raise NotFittedError(msg % {'name': type(estimator).__name__})
sklearn.exceptions.NotFittedError: This MultinomialNB instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RunEnsembleMethodsDWT.py", line 196, in <module>
    meta.fit(X_dsel, y_dsel)
  File "/home/miner/anaconda2/envs/python35/lib/python3.5/site-packages/deslib/des/meta_des.py", line 135, in fit
    self._train_meta_classifier()
  File "/home/miner/anaconda2/envs/python35/lib/python3.5/site-packages/deslib/des/meta_des.py", line 242, in _train_meta_classifier
    self.meta_classifier.fit(self.meta_training_dataset, self.meta_training_target)
  File "/home/miner/anaconda2/envs/python35/lib/python3.5/site-packages/sklearn/naive_bayes.py", line 579, in fit
    X, y = check_X_y(X, y, 'csr')
  File "/home/miner/anaconda2/envs/python35/lib/python3.5/site-packages/sklearn/utils/validation.py", line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "/home/miner/anaconda2/envs/python35/lib/python3.5/site-packages/sklearn/utils/validation.py", line 441, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by Menelau** [comment]
Hello,

By the error message, it seems that the meta-training dataset being passed for the training of the meta-classifier is an empty array. So that means no meta-feature vectors are being generated in the meta-training process. This could happen if the majority of base classifiers (if not all) always produces the same labels for the training data. Which are the value of the hyper-parameter Hc and the size of the pool/type of base classifiers that you are using? 

Anyway, this problems also means that the META-DES implementation needs to have a few extra checks, and raise an exception to warn the user when no meta-training data is generated in the training process due to the base classifiers always agreeing with the same answer. I will work on it now.

**Comment by alzami1986** [comment]
Hello, thank you for the response. In here, I am using this configuration:
# start the model
my_clf = DecisionTreeClassifier()

model            = CalibratedClassifierCV(my_clf,cv=N_CV)
pool_classifiers = BaggingClassifier(model,n_estimators=N_estimator)
pool_classifiers.fit(X_train_des,y_train_des)

# initialize the DES technique
meta   = METADES(pool_classifiers, Hc=0.8)

# fit the DES tehcnique
meta.fit(X_dsel, y_dsel)

# run for accuracy
result_meta_clf            = meta.score(X_test,y_test)

**Comment by Menelau** [comment]
Hi, 
Can you try changing the value of Hc to either 0.9 or .01, to confirm the problem is really with the sample selection mechanism discarding all meta training examples due to the base classifiers agreeing with the same output?

**Comment by alzami1986** [comment]
Hello,

alright, please wait a while
